=== ascmitc/mhl/xsd/ASCMHL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
    targetNamespace="http://theasc.com/ASCMHL" 
    elementFormDefault="qualified"
    xmlns="http://www.w3.org/2001/XMLSchema" 
    xmlns:ascmhl="http://theasc.com/ASCMHL">
    
    <simpleType name="EmailAddressAttributeType">
        <restriction base="string">
            <pattern value="[^@]+@[^\.]+\..+"/>
        </restriction>
    </simpleType>
    <simpleType name="ActionAttributeType">
        <restriction base="string">
            <enumeration value="original"/>
            <enumeration value="new"/>
            <enumeration value="verified"/>
            <enumeration value="failed"/>
        </restriction>
    </simpleType>
    <simpleType name="DirectoryAttributeType">
        <restriction base="string">
            <enumeration value="true"/>
            <enumeration value="false"/>
        </restriction>
    </simpleType>
    
    <complexType name="HashListType">
        <sequence>
            <element name="creatorinfo" type="ascmhl:CreatorInfoType"/>
            <element name="metadata" type="ascmhl:MetadataType" minOccurs="0"/>
            <element name="hashes" type="ascmhl:HashesType" minOccurs="1"/>
        </sequence>
        <attribute fixed="2" name="version" use="required"/>
    </complexType>
    <complexType name="CreatorInfoType">
        <sequence>
            <element name="creationdate" type="dateTime" maxOccurs="1" minOccurs="1"/>
            <element name="tool" type="ascmhl:ToolType" maxOccurs="1" minOccurs="1"/>
            <element name="hostname" type="string" maxOccurs="1" minOccurs="1"/>
            <element maxOccurs="unbounded" minOccurs="0" name="author" type="ascmhl:AuthorType"/>
            <element minOccurs="0" name="location"/>
            <element name="process" type="ascmhl:ProcessType" maxOccurs="1" minOccurs="1"/>
            <element name="ignore" type="ascmhl:IgnoreType" minOccurs="0"/>
        </sequence>
    </complexType>
    <complexType name="AuthorType">
        <simpleContent>
            <extension base="string">
                <attribute name="email" type="ascmhl:EmailAddressAttributeType"/>
                <attribute name="phone" type="string"/>
                <attribute name="role" type="string"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="ToolType">
        <simpleContent>
            <extension base="string">
                <attribute name="version" type="string"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType block="" name="ProcessType">
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="in-place"/>
                    <enumeration value="transfer"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="hashsource" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="file"/>
                    <enumeration value="source"/>
                    <enumeration value="source+file"/>
                    <enumeration value="other"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="IgnoreType">
        <sequence>
            <element maxOccurs="unbounded" name="pattern" type="string"/>
        </sequence>
    </complexType>
    <complexType name="HashesType">
        <sequence>
            <element name="hash" type="ascmhl:HashType" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
        <attribute name="rootpath" type="string" use="required"/>
    </complexType>
    <complexType name="HashType">
        <sequence>
            <element name="path" type="string"/>
            <element name="filesize" type="int" minOccurs="0" nillable="false"/>
            <element name="lastmodificationdate" type="dateTime"/>
            <sequence maxOccurs="unbounded">
                <element name="md5" type="ascmhl:HashFormatType" minOccurs="0"/>
                <element name="sha1" type="ascmhl:HashFormatType" minOccurs="0"/>
                <element name="c4" type="ascmhl:HashFormatType" minOccurs="0"/>
                <element name="xxh32" type="ascmhl:HashFormatType" maxOccurs="1" minOccurs="0"/>
                <element name="xxh64" type="ascmhl:HashFormatType" maxOccurs="1" minOccurs="0"/>
                <element name="xxh3" type="ascmhl:HashFormatType" maxOccurs="1" minOccurs="0"/>
            </sequence>
            <element minOccurs="0" name="metadata" type="ascmhl:MetadataType"/>
        </sequence>
        <attribute name="directory" type="ascmhl:DirectoryAttributeType"/>
    </complexType>
    <complexType name="HashFormatType">
        <simpleContent>
            <extension base="string">
                <attribute name="action" type="ascmhl:ActionAttributeType"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="MetadataType">
        <complexContent>
            <extension base="anyType"/>
        </complexContent>
    </complexType>
    <element name="hashlist" type="ascmhl:HashListType"/>
</schema>

=== ascmitc/mhl/xsd/examples/test_01_0001.xml
<?xml version="1.0" encoding="UTF-8"?>
<hashlist version="2"
xmlns="http://theasc.com/ASCMHL" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://theasc.com/ASCMHL/ASCMHL ASCMHL.xsd">
  <creatorinfo>
    <creationdate>2019-10-11T15:56:03+02:00</creationdate>
    <tool version="0.0.3">ascmhl-tool</tool>
    <hostname>donkey.local</hostname>
    <author email="foo@bar.foo.foo.com" phone="+1 234 567 890 88">Liz Foo</author>
    <author email="zed@bar.foo.foo.com" phone="+1 234 567 890 99">Ben Zed</author>
    <location>Munich, Germany</location>
    <process type="in-place" />
    <ignore>
      <pattern>.DSStore</pattern>      
    </ignore>
  </creatorinfo>
  <metadata>
    test
    <foo bar="1">lorem</foo>
  </metadata>
  <hashes rootPath="/Users/ptr/Development/MediaHashList/mhl/Scenarios/Output/scenario_01/A002R2EC/">
    <hash>
      <path>Clips/A002C006_141024_R2EC.mov</path>
      <filesize>5</filesize>
      <lastmodificationdate>2019-10-11T15:56:03+02:00</lastmodificationdate>
      <xxh64 action="original">0ea03b369a463d9d</xxh64>
    </hash>
    <hash>
      <path>Clips/A002C007_141024_R2EC.mov</path>
      <filesize>4</filesize>
      <lastmodificationdate>2019-10-11T15:56:03+02:00</lastmodificationdate>
      <xxh64 action="original">7680e5f98f4a80fd</xxh64>
    </hash>
    <hash directory="true">
      <path>Clips/</path>
      <lastmodificationdate>2019-10-11T15:56:05+02:00</lastmodificationdate>
      <xxh64>7680e5f98f4a80fd</xxh64>
      <metadata>test2</metadata>
    </hash>
    <hash>
      <path>Sidecar.txt</path>
      <filesize>58</filesize>
      <lastmodificationdate>2019-10-11T15:56:03+02:00</lastmodificationdate>
      <xxh64 action="original">3ab5a4166b9bde44</xxh64>
      <metadata bar="Foo" />
    </hash>
  </hashes>
</hashlist>
